apiVersion : apps/v1
kind: Deployment
metadata:
  name: registration 
  labels:
    app: registration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration 
    spec:
      containers:
        - name: registration
          env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Logging__MinimumLevel 
            value: Information 
          - name: Orleans__MembershipProvider__Name
            value: Kubernetes
          - name: Orleans__Streams__Kafka__Brokers
            value: cp-kafka:9092
          image: fluffyspoon.azurecr.io/registration
          ports:
          - containerPort: 8080
          livenessProbe:
              httpGet:
                  path: actuator/health/live
                  port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
          readinessProbe:
              httpGet:
                  path: actuator/health/ready
                  port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
