apiVersion: v1
kind: Service
metadata:
    name: registration
spec:
    type: LoadBalancer
    ports:
    - port: 8080
    livenessProbe:
        httpGet:
            path: actuator/health/live
            port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
    readinessProbe:
        httpGet:
            path: actuator/health/ready
            port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
    selector:
        app: registration