apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kafka 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka 
    spec:
      containers:
        - name: kafka
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_ADVERTISED_LISTENERS 
            value: PLAINTEXT://kafka:9092 
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: 1
          image: confluentinc/cp-kafka:latest
          ports:
          - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    type: ClusterIP
    ports:
    - port: 9092
    selector:
        app: kafka