version: '3.4'

services:
  registration:
    image: fluffyspoon.registration
    build:
      dockerfile: src/fluffyspoon.registration/Dockerfile
      context: ..
    environment:
      - ASPNETCORE_URLS=http://+:8080
